"""Initial migration.

Revision ID: 070ca1087fb8
Revises: 650cfa4e35c1
Create Date: 2023-04-29 17:55:12.835074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070ca1087fb8'
down_revision = '650cfa4e35c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marvel_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comics', sa.String(length=10000), nullable=True))
        batch_op.drop_column('comics_appeared_in')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marvel_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comics_appeared_in', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('comics')

    # ### end Alembic commands ###
